apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-list-hackathon.fullname" . }}-{{ .Values.component.name }}
  labels:
    app: {{ .Values.component.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ .Values.component.name }}
