apiVersion: v2
name: todo-list-hackathon
description: A Helm chart for Todo List Hackathon application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - task-manager
maintainers:
  - name: GrowWidTalha
    email: growwithtalha2@gmail.com
